name: Keep Supabase Alive

on:
  schedule:
    # Runs at 00:00 (UTC) on Sunday (0) and Thursday (4)
    - cron: '0 0 * * 0,4'
  workflow_dispatch: # Allows you to trigger it manually for testing

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Make API request to Supabase
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/messages?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
          echo "Supabase pinged successfully."
